version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hack_site
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: astrocatling/backend:latest
    build: ./back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hack_site
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    image: astrocatling/frontend:latest
    build: ./front
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hack_site
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "80:80"

volumes:
  postgres_data:
