spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  token: 4b613c8ed64c3ba25eb1cf97688eadefc7b85ad1b24fdabe037be11aba7cd604